name: CampusHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Backend
        run: |
          cd backend
          npm install

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
